services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
  Networkteam\FilesystemGarbageCollection\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'
  Networkteam\FilesystemGarbageCollection\Command\CleanupFolderCommand:
    tags:
      -
        name: console.command
        command: 'cleanup:folder'
        description: 'Removes files by given maximum age and folder'
        schedulable: true
